<a href="https://colab.research.google.com/github/Kushisuvarna/program/blob/main/carpricek.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np

In [2]:
car=pd.read_csv('/content/used_car_dataset.csv')

In [3]:
car.head()

,car_name,car_price_in_rupees,kms_driven,fuel_type,city,year_of_manufacture
0,Hyundai Grand i10 Magna 1.2 Kappa VTVT [2017-2...,₹ 4.45 Lakh,"22,402 km",Petrol,Mumbai,2016
1,Maruti Suzuki Alto 800 Lxi,₹ 2.93 Lakh,"10,344 km",Petrol,Kolkata,2019
2,Tata Safari XZ Plus New,₹ 22.49 Lakh,"12,999 km",Diesel,Bangalore,2021
3,Maruti Suzuki Ciaz ZXI+,₹ 6.95 Lakh,"45,000 km",Petrol,Thane,2016
4,Jeep Compass Sport Plus 1.4 Petrol [2019-2020],₹ 12 Lakh,"11,193 km",Petrol,Kolkata,2019

In [4]:
car.shape

(2105, 6)

In [5]:
car.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2105 entries, 0 to 2104
Data columns (total 6 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   car_name             2105 non-null   object
 1   car_price_in_rupees  2105 non-null   object
 2   kms_driven           2105 non-null   object
 3   fuel_type            2105 non-null   object
 4   city                 2105 non-null   object
 5   year_of_manufacture  2105 non-null   int64
dtypes: int64(1), object(5)
memory usage: 98.8+ KB

In [6]:
car['year_of_manufacture'].unique()

array([2016, 2019, 2021, 2017, 2013, 2018, 2007, 2022, 2014, 2020, 2015,
       2009, 2011, 2010, 2012, 2008, 2006, 2004, 2005])

In [7]:
car['car_price_in_rupees'].unique()

array(['₹ 4.45 Lakh', '₹ 2.93 Lakh', '₹ 22.49 Lakh', '₹ 6.95 Lakh',
       '₹ 12 Lakh', '₹ 3.72 Lakh', '₹ 11.5 Lakh', '₹ 10.39 Lakh',
       '₹ 3.75 Lakh', '₹ 4.25 Lakh', '₹ 6.75 Lakh', '₹ 4.49 Lakh',
       '₹ 3 Lakh', '₹ 9.5 Lakh', '₹ 13.25 Lakh', '₹ 9.25 Lakh',
       '₹ 95 Lakh', '₹ 8.71 Lakh', '₹ 3.35 Lakh', '₹ 9.88 Lakh',
       '₹ 1.15 Crore', '₹ 11 Lakh', '₹ 9.9 Lakh', '₹ 3.45 Lakh',
       '₹ 37.49 Lakh', '₹ 6.39 Lakh', '₹ 8.9 Lakh', '₹ 6.59 Lakh',
       '₹ 3.92 Lakh', '₹ 8 Lakh', '₹ 7.75 Lakh', '₹ 11.52 Lakh',
       '₹ 16.75 Lakh', '₹ 8.5 Lakh', '₹ 5.93 Lakh', '₹ 4.15 Lakh',
       '₹ 18.5 Lakh', '₹ 2.4 Lakh', '₹ 11.99 Lakh', '₹ 8.95 Lakh',
       '₹ 9.68 Lakh', '₹ 81 Lakh', '₹ 4.93 Lakh', '₹ 10.5 Lakh',
       '₹ 7.85 Lakh', '₹ 38.99 Lakh', '₹ 31 Lakh', '₹ 4.85 Lakh',
       '₹ 4.35 Lakh', '₹ 4.51 Lakh', '₹ 5.45 Lakh', '₹ 4.5 Lakh',
       '₹ 6.81 Lakh', '₹ 3.95 Lakh', '₹ 11.43 Lakh', '₹ 23 Lakh',
       '₹ 12.75 Lakh', '₹ 5.99 Lakh', '₹ 16.2 Lakh', '₹ 4.2 Lakh',
       '₹ 4.75 Lakh', '₹ 66 Lakh', '₹ 68.99 Lakh', '₹ 4.41 Lakh',
       '₹ 29.5 Lakh', '₹ 5.9 Lakh', '₹ 4.14 Lakh', '₹ 2.85 Lakh',
       '₹ 7.1 Lakh', '₹ 13.95 Lakh', '₹ 3.2 Lakh', '₹ 6.29 Lakh',
       '₹ 6.51 Lakh', '₹ 2.89 Lakh', '₹ 8.97 Lakh', '₹ 2.76 Lakh',
       '₹ 6.9 Lakh', '₹ 10.44 Lakh', '₹ 7.35 Lakh', '₹ 3.9 Lakh',
       '₹ 25 Lakh', '₹ 11.25 Lakh', '₹ 9.79 Lakh', '₹ 4.99 Lakh',
       '₹ 16.59 Lakh', '₹ 4.76 Lakh', '₹ 7.39 Lakh', '₹ 6.28 Lakh',
       '₹ 4.09 Lakh', '₹ 7.95 Lakh', '₹ 11.9 Lakh', '₹ 2.99 Lakh',
       '₹ 3.91 Lakh', '₹ 5.8 Lakh', '₹ 19.25 Lakh', '₹ 3.4 Lakh',
       '₹ 6.33 Lakh', '₹ 3.96 Lakh', '₹ 24.75 Lakh', '₹ 4.91 Lakh',
       '₹ 7.4 Lakh', '₹ 5.85 Lakh', '₹ 3.85 Lakh', '₹ 42.5 Lakh',
       '₹ 7.99 Lakh', '₹ 18.9 Lakh', '₹ 4.07 Lakh', '₹ 8.3 Lakh',
       '₹ 7.6 Lakh', '₹ 9.55 Lakh', '₹ 8.75 Lakh', '₹ 2.5 Lakh',
       '₹ 14 Lakh', '₹ 5.95 Lakh', '₹ 6.79 Lakh', '₹ 6.6 Lakh',
       '₹ 6.87 Lakh', '₹ 3.04 Lakh', '₹ 5.29 Lakh', '₹ 4.16 Lakh',
       '₹ 3.01 Lakh', '₹ 9.41 Lakh', '₹ 23.75 Lakh', '₹ 4.9 Lakh',
       '₹ 3.31 Lakh', '₹ 2.35 Lakh', '₹ 13.9 Lakh', '₹ 21.5 Lakh',
       '₹ 12.04 Lakh', '₹ 5.57 Lakh', '₹ 5.79 Lakh', '₹ 5.54 Lakh',
       '₹ 43 Lakh', '₹ 18.95 Lakh', '₹ 10 Lakh', '₹ 8.85 Lakh',
       '₹ 4.84 Lakh', '₹ 7.15 Lakh', '₹ 4.62 Lakh', '₹ 34.99 Lakh',
       '₹ 10.25 Lakh', '₹ 1.8 Lakh', '₹ 16 Lakh', '₹ 20.95 Lakh',
       '₹ 4.6 Lakh', '₹ 3.42 Lakh', '₹ 6.85 Lakh', '₹ 2.1 Lakh',
       '₹ 41 Lakh', '₹ 10.75 Lakh', '₹ 17.99 Lakh', '₹ 7.11 Lakh',
       '₹ 11.49 Lakh', '₹ 5.24 Lakh', '₹ 19 Lakh', '₹ 7.5 Lakh',
       '₹ 12.85 Lakh', '₹ 8.55 Lakh', '₹ 8.99 Lakh', '₹ 3.48 Lakh',
       '₹ 8.11 Lakh', '₹ 5.67 Lakh', '₹ 21 Lakh', '₹ 5.25 Lakh',
       '₹ 22.57 Lakh', '₹ 5.75 Lakh', '₹ 7.45 Lakh', '₹ 7.08 Lakh',
       '₹ 3.38 Lakh', '₹ 4.34 Lakh', '₹ 61.75 Lakh', '₹ 32 Lakh',
       '₹ 8.72 Lakh', '₹ 6.5 Lakh', '₹ 4.95 Lakh', '₹ 15.25 Lakh',
       '₹ 4.32 Lakh', '₹ 7.25 Lakh', '₹ 4.33 Lakh', '₹ 7.2 Lakh',
       '₹ 16.95 Lakh', '₹ 5.1 Lakh', '₹ 5.65 Lakh', '₹ 2.25 Lakh',
       '₹ 19.99 Lakh', '₹ 37.75 Lakh', '₹ 32.5 Lakh', '₹ 44 Lakh',
       '₹ 4.65 Lakh', '₹ 4.53 Lakh', '₹ 5.34 Lakh', '₹ 2.05 Lakh',
       '₹ 15.5 Lakh', '₹ 17.9 Lakh', '₹ 5.38 Lakh', '₹ 57.5 Lakh',
       '₹ 6.3 Lakh', '₹ 46 Lakh', '₹ 21.75 Lakh', '₹ 59 Lakh',
       '₹ 9.98 Lakh', '₹ 3.25 Lakh', '₹ 16.9 Lakh', '₹ 4.3 Lakh',
       '₹ 3.3 Lakh', '₹ 59.5 Lakh', '₹ 6.13 Lakh', '₹ 5.59 Lakh',
       '₹ 68 Lakh', '₹ 16.99 Lakh', '₹ 14.9 Lakh', '₹ 17.1 Lakh',
       '₹ 3.13 Lakh', '₹ 3.32 Lakh', '₹ 26.5 Lakh', '₹ 9.75 Lakh',
       '₹ 3.5 Lakh', '₹ 35 Lakh', '₹ 4.06 Lakh', '₹ 5.4 Lakh', '₹ 5 Lakh',
       '₹ 16.49 Lakh', '₹ 8.83 Lakh', '₹ 6.74 Lakh', '₹ 4.05 Lakh',
       '₹ 78.57 Lakh', '₹ 4.17 Lakh', '₹ 4.83 Lakh', '₹ 5.89 Lakh',
       '₹ 2.9 Lakh', '₹ 5.49 Lakh', '₹ 10.64 Lakh', '₹ 77 Lakh',
       '₹ 10.59 Lakh', '₹ 3.17 Lakh', '₹ 10.4 Lakh', '₹ 1.23 Crore',
       '₹ 4.71 Lakh', '₹ 7.49 Lakh', '₹ 7.47 Lakh', '₹ 1.9 Lakh',
       '₹ 6.45 Lakh', '₹ 3.26 Lakh', '₹ 21.45 Lakh', '₹ 9.51 Lakh',
       '₹ 14.65 Lakh', '₹ 28 Lakh', '₹ 58 Lakh', '₹ 6.11 Lakh',
       '₹ 64.5 Lakh', '₹ 6 Lakh', '₹ 6.25 Lakh', '₹ 11.26 Lakh',
       '₹ 30.56 Lakh', '₹ 3.57 Lakh', '₹ 5.21 Lakh', '₹ 4.39 Lakh',
       '₹ 45.99 Lakh', '₹ 14.19 Lakh', '₹ 4.89 Lakh', '₹ 10.29 Lakh',
       '₹ 22.87 Lakh', '₹ 7.9 Lakh', '₹ 8.45 Lakh', '₹ 8.49 Lakh',
       '₹ 5.35 Lakh', '₹ 5.69 Lakh', '₹ 33.75 Lakh', '₹ 10.82 Lakh',
       '₹ 6.99 Lakh', '₹ 5.23 Lakh', '₹ 5.48 Lakh', '₹ 5.19 Lakh',
       '₹ 1.1 Lakh', '₹ 11.4 Lakh', '₹ 7.21 Lakh', '₹ 8.87 Lakh',
       '₹ 2.95 Lakh', '₹ 17.5 Lakh', '₹ 8.25 Lakh', '₹ 26 Lakh',
       '₹ 6.66 Lakh', '₹ 10.66 Lakh', '₹ 3.49 Lakh', '₹ 2.45 Lakh',
       '₹ 65 Lakh', '₹ 18.75 Lakh', '₹ 4.24 Lakh', '₹ 5.96 Lakh',
       '₹ 28.5 Lakh', '₹ 8.4 Lakh', '₹ 6.96 Lakh', '₹ 8.1 Lakh',
       '₹ 33 Lakh', '₹ 22 Lakh', '₹ 17.25 Lakh', '₹ 7.3 Lakh',
       '₹ 6.7 Lakh', '₹ 8.42 Lakh', '₹ 36 Lakh', '₹ 8.15 Lakh',
       '₹ 8.79 Lakh', '₹ 10.19 Lakh', '₹ 5.18 Lakh', '₹ 3.79 Lakh',
       '₹ 8.65 Lakh', '₹ 9.3 Lakh', '₹ 1.6 Lakh', '₹ 6.65 Lakh',
       '₹ 20.5 Lakh', '₹ 9.8 Lakh', '₹ 7.04 Lakh', '₹ 6.1 Lakh',
       '₹ 48.5 Lakh', '₹ 6.53 Lakh', '₹ 6.2 Lakh', '₹ 47.9 Lakh',
       '₹ 5.27 Lakh', '₹ 28.78 Lakh', '₹ 6.15 Lakh', '₹ 12.9 Lakh',
       '₹ 10.13 Lakh', '₹ 7 Lakh', '₹ 17.49 Lakh', '₹ 24.49 Lakh',
       '₹ 8.57 Lakh', '₹ 4.54 Lakh', '₹ 22.5 Lakh', '₹ 14.75 Lakh',
       '₹ 2.92 Lakh', '₹ 18.25 Lakh', '₹ 5.26 Lakh', '₹ 60,000',
       '₹ 3.1 Lakh', '₹ 6.55 Lakh', '₹ 16.85 Lakh', '₹ 4.64 Lakh',
       '₹ 16.92 Lakh', '₹ 22.95 Lakh', '₹ 3.59 Lakh', '₹ 7.33 Lakh',
       '₹ 33.5 Lakh', '₹ 6.49 Lakh', '₹ 8.2 Lakh', '₹ 11.37 Lakh',
       '₹ 2.23 Lakh', '₹ 9.45 Lakh', '₹ 2.67 Lakh', '₹ 9.49 Lakh',
       '₹ 3.27 Lakh', '₹ 3.7 Lakh', '₹ 12.51 Lakh', '₹ 47.5 Lakh',
       '₹ 48 Lakh', '₹ 9.85 Lakh', '₹ 27.5 Lakh', '₹ 7.12 Lakh',
       '₹ 5.56 Lakh', '₹ 10.2 Lakh', '₹ 5.7 Lakh', '₹ 15 Lakh',
       '₹ 19.5 Lakh', '₹ 10.65 Lakh', '₹ 93 Lakh', '₹ 51.95 Lakh',
       '₹ 32.6 Lakh', '₹ 4.46 Lakh', '₹ 5.42 Lakh', '₹ 12.25 Lakh',
       '₹ 7.31 Lakh', '₹ 53 Lakh', '₹ 15.13 Lakh', '₹ 11.55 Lakh',
       '₹ 15.74 Lakh', '₹ 2.98 Lakh', '₹ 5.5 Lakh', '₹ 4.82 Lakh',
       '₹ 14.25 Lakh', '₹ 5.6 Lakh', '₹ 8.62 Lakh', '₹ 4.63 Lakh',
       '₹ 9 Lakh', '₹ 9.91 Lakh', '₹ 7.61 Lakh', '₹ 7.79 Lakh',
       '₹ 3.76 Lakh', '₹ 2.65 Lakh', '₹ 3.69 Lakh', '₹ 6.54 Lakh',
       '₹ 3.51 Lakh', '₹ 3.8 Lakh', '₹ 9.11 Lakh', '₹ 19.75 Lakh',
       '₹ 3.15 Lakh', '₹ 8.59 Lakh', '₹ 10.03 Lakh', '₹ 6.73 Lakh',
       '₹ 78.99 Lakh', '₹ 13.83 Lakh', '₹ 3.19 Lakh', '₹ 24 Lakh',
       '₹ 61.5 Lakh', '₹ 21.43 Lakh', '₹ 4 Lakh', '₹ 74 Lakh',
       '₹ 4.79 Lakh', '₹ 13.5 Lakh', '₹ 8.51 Lakh', '₹ 14.91 Lakh',
       '₹ 42.75 Lakh', '₹ 6.37 Lakh', '₹ 4.77 Lakh', '₹ 5.36 Lakh',
       '₹ 30 Lakh', '₹ 16.11 Lakh', '₹ 19.9 Lakh', '₹ 26.49 Lakh',
       '₹ 7.78 Lakh', '₹ 6.83 Lakh', '₹ 5.64 Lakh', '₹ 3.05 Lakh',
       '₹ 14.99 Lakh', '₹ 7.7 Lakh', '₹ 19.2 Lakh', '₹ 10.9 Lakh',
       '₹ 3.89 Lakh', '₹ 6.34 Lakh', '₹ 9.96 Lakh', '₹ 11.17 Lakh',
       '₹ 22.51 Lakh', '₹ 18.66 Lakh', '₹ 8.8 Lakh', '₹ 6.89 Lakh',
       '₹ 4.1 Lakh', '₹ 4.86 Lakh', '₹ 3.64 Lakh', '₹ 13.75 Lakh',
       '₹ 15.8 Lakh', '₹ 3.61 Lakh', '₹ 1.75 Lakh', '₹ 4.28 Lakh',
       '₹ 10.24 Lakh', '₹ 7.65 Lakh', '₹ 23.95 Lakh', '₹ 69.75 Lakh',
       '₹ 5.3 Lakh', '₹ 5.53 Lakh', '₹ 6.69 Lakh', '₹ 15.79 Lakh',
       '₹ 1.5 Lakh', '₹ 13 Lakh', '₹ 7.23 Lakh', '₹ 5.58 Lakh',
       '₹ 6.18 Lakh', '₹ 3.78 Lakh', '₹ 9.99 Lakh', '₹ 10.99 Lakh',
       '₹ 9.13 Lakh', '₹ 6.86 Lakh', '₹ 8.47 Lakh', '₹ 4.11 Lakh',
       '₹ 2.7 Lakh', '₹ 9.22 Lakh', '₹ 5.31 Lakh', '₹ 24.26 Lakh',
       '₹ 7.69 Lakh', '₹ 29.75 Lakh', '₹ 12.13 Lakh', '₹ 9.54 Lakh',
       '₹ 9.31 Lakh', '₹ 49.5 Lakh', '₹ 10.95 Lakh', '₹ 6.52 Lakh',
       '₹ 6.21 Lakh', '₹ 61 Lakh', '₹ 9.74 Lakh', '₹ 10.23 Lakh',
       '₹ 16.82 Lakh', '₹ 4.19 Lakh', '₹ 4.87 Lakh', '₹ 2.82 Lakh',
       '₹ 4.52 Lakh', '₹ 9.1 Lakh', '₹ 16.5 Lakh', '₹ 13.53 Lakh',
       '₹ 12.5 Lakh', '₹ 5.71 Lakh', '₹ 10.76 Lakh', '₹ 7.19 Lakh',
       '₹ 3.09 Lakh', '₹ 18.99 Lakh', '₹ 10.72 Lakh', '₹ 20.31 Lakh',
       '₹ 27.51 Lakh', '₹ 32.75 Lakh', '₹ 6.41 Lakh', '₹ 7.89 Lakh',
       '₹ 38 Lakh', '₹ 2.09 Lakh', '₹ 9.78 Lakh', '₹ 14.56 Lakh',
       '₹ 3.99 Lakh', '₹ 4.61 Lakh', '₹ 6.4 Lakh', '₹ 23.76 Lakh',
       '₹ 24.85 Lakh', '₹ 7.91 Lakh', '₹ 11.95 Lakh', '₹ 24.5 Lakh',
       '₹ 5.11 Lakh', '₹ 10.45 Lakh', '₹ 7.59 Lakh', '₹ 3.21 Lakh',
       '₹ 18 Lakh', '₹ 2.69 Lakh', '₹ 6.44 Lakh', '₹ 5.55 Lakh',
       '₹ 2.34 Lakh', '₹ 15.3 Lakh', '₹ 2.68 Lakh', '₹ 33.25 Lakh',
       '₹ 6.48 Lakh', '₹ 5.44 Lakh', '₹ 7.55 Lakh', '₹ 2.2 Lakh',
       '₹ 11.75 Lakh', '₹ 19.56 Lakh', '₹ 10.12 Lakh', '₹ 30.5 Lakh',
       '₹ 25.59 Lakh', '₹ 9.36 Lakh', '₹ 19.4 Lakh', '₹ 2 Lakh',
       '₹ 21.49 Lakh', '₹ 4.08 Lakh', '₹ 44.5 Lakh', '₹ 12.99 Lakh',
       '₹ 9.42 Lakh', '₹ 15.95 Lakh', '₹ 8.32 Lakh', '₹ 17.45 Lakh',
       '₹ 4.8 Lakh', '₹ 3.36 Lakh', '₹ 15.9 Lakh', '₹ 37 Lakh',
       '₹ 8.68 Lakh', '₹ 10.46 Lakh', '₹ 11.71 Lakh', '₹ 5.92 Lakh',
       '₹ 9.83 Lakh', '₹ 4.69 Lakh', '₹ 6.58 Lakh', '₹ 5.37 Lakh',
       '₹ 4.31 Lakh', '₹ 27 Lakh', '₹ 3.67 Lakh', '₹ 10.97 Lakh',
       '₹ 27.85 Lakh', '₹ 14.5 Lakh', '₹ 39.5 Lakh', '₹ 16.31 Lakh',
       '₹ 15.98 Lakh', '₹ 8.43 Lakh', '₹ 9.59 Lakh', '₹ 11.45 Lakh',
       '₹ 12.27 Lakh', '₹ 20 Lakh', '₹ 15.99 Lakh', '₹ 5.15 Lakh',
       '₹ 7.52 Lakh', '₹ 6.04 Lakh', '₹ 2.46 Lakh', '₹ 20.7 Lakh',
       '₹ 2.83 Lakh', '₹ 9.65 Lakh', '₹ 3.43 Lakh', '₹ 4.74 Lakh',
       '₹ 3.14 Lakh', '₹ 64.99 Lakh', '₹ 26.99 Lakh', '₹ 53.55 Lakh',
       '₹ 5.94 Lakh', '₹ 27.99 Lakh', '₹ 69.95 Lakh', '₹ 41.99 Lakh',
       '₹ 43.07 Lakh', '₹ 63 Lakh', '₹ 3.82 Lakh', '₹ 2.55 Lakh',
       '₹ 8.35 Lakh', '₹ 8.13 Lakh', '₹ 18.51 Lakh', '₹ 46.6 Lakh',
       '₹ 5.2 Lakh', '₹ 85 Lakh', '₹ 4.01 Lakh', '₹ 7.67 Lakh',
       '₹ 5.43 Lakh', '₹ 17 Lakh', '₹ 3.22 Lakh', '₹ 7.17 Lakh',
       '₹ 3.65 Lakh', '₹ 4.98 Lakh', '₹ 10.6 Lakh', '₹ 9.95 Lakh',
       '₹ 4.68 Lakh', '₹ 5.47 Lakh', '₹ 21.8 Lakh', '₹ 42.99 Lakh',
       '₹ 4.4 Lakh', '₹ 6.57 Lakh', '₹ 1.99 Lakh', '₹ 3.39 Lakh',
       '₹ 19.19 Lakh', '₹ 5.97 Lakh', '₹ 6.09 Lakh', '₹ 8.28 Lakh',
       '₹ 11.05 Lakh', '₹ 3.66 Lakh', '₹ 8.12 Lakh', '₹ 35.95 Lakh',
       '₹ 5.66 Lakh', '₹ 10.27 Lakh', '₹ 5.39 Lakh', '₹ 31.75 Lakh',
       '₹ 1.19 Crore', '₹ 9.92 Lakh', '₹ 8.39 Lakh', '₹ 1.85 Lakh',
       '₹ 7.29 Lakh', '₹ 32.99 Lakh', '₹ 8.04 Lakh', '₹ 4.48 Lakh',
       '₹ 14.45 Lakh', '₹ 29 Lakh', '₹ 9.01 Lakh', '₹ 14.35 Lakh',
       '₹ 4.7 Lakh', '₹ 7.02 Lakh', '₹ 12.6 Lakh', '₹ 1.95 Crore',
       '₹ 11.61 Lakh', '₹ 3.87 Lakh', '₹ 9.56 Lakh', '₹ 22.99 Lakh',
       '₹ 8.31 Lakh', '₹ 15.51 Lakh', '₹ 2.49 Lakh', '₹ 9.6 Lakh',
       '₹ 15.23 Lakh', '₹ 3.94 Lakh', '₹ 3.6 Lakh', '₹ 4.55 Lakh',
       '₹ 9.29 Lakh', '₹ 12.24 Lakh', '₹ 52 Lakh', '₹ 10.63 Lakh',
       '₹ 23.49 Lakh', '₹ 3.29 Lakh', '₹ 49 Lakh', '₹ 9.64 Lakh',
       '₹ 2.86 Lakh', '₹ 13.2 Lakh', '₹ 9.7 Lakh', '₹ 16.67 Lakh',
       '₹ 8.14 Lakh', '₹ 16.25 Lakh', '₹ 7.37 Lakh', '₹ 6.06 Lakh',
       '₹ 5.09 Lakh', '₹ 15.21 Lakh', '₹ 31.25 Lakh', '₹ 59.99 Lakh',
       '₹ 6.07 Lakh', '₹ 29.95 Lakh', '₹ 8.53 Lakh', '₹ 72 Lakh',
       '₹ 20.49 Lakh', '₹ 22.25 Lakh', '₹ 17.95 Lakh', '₹ 10.02 Lakh',
       '₹ 13.69 Lakh', '₹ 8.08 Lakh', '₹ 15.45 Lakh', '₹ 1.81 Lakh',
       '₹ 10.87 Lakh', '₹ 3.73 Lakh', '₹ 28.75 Lakh', '₹ 5.81 Lakh',
       '₹ 10.06 Lakh', '₹ 26.75 Lakh', '₹ 3.41 Lakh', '₹ 32.95 Lakh',
       '₹ 10.67 Lakh', '₹ 2.6 Lakh', '₹ 4.02 Lakh', '₹ 5.62 Lakh',
       '₹ 9.39 Lakh', '₹ 6.35 Lakh', '₹ 44.37 Lakh', '₹ 8.66 Lakh',
       '₹ 19.95 Lakh', '₹ 8.56 Lakh', '₹ 19.45 Lakh', '₹ 11.3 Lakh',
       '₹ 3.84 Lakh', '₹ 8.91 Lakh', '₹ 99,991', '₹ 6.8 Lakh',
       '₹ 17.91 Lakh', '₹ 3.23 Lakh', '₹ 5.51 Lakh', '₹ 22.88 Lakh',
       '₹ 2.91 Lakh', '₹ 1.42 Lakh', '₹ 12.49 Lakh', '₹ 25.5 Lakh',
       '₹ 45 Lakh', '₹ 15.4 Lakh', '₹ 70 Lakh', '₹ 10.11 Lakh',
       '₹ 11.57 Lakh', '₹ 9.14 Lakh', '₹ 12.56 Lakh', '₹ 7.93 Lakh',
       '₹ 12.65 Lakh', '₹ 4.94 Lakh', '₹ 2.01 Lakh', '₹ 4.27 Lakh',
       '₹ 10.93 Lakh', '₹ 11.79 Lakh', '₹ 7.64 Lakh', '₹ 11.56 Lakh',
       '₹ 5.82 Lakh', '₹ 10.22 Lakh', '₹ 11.04 Lakh', '₹ 6.23 Lakh',
       '₹ 15.75 Lakh', '₹ 11.35 Lakh', '₹ 2.39 Lakh', '₹ 54 Lakh',
       '₹ 8.21 Lakh', '₹ 4.96 Lakh', '₹ 37.85 Lakh', '₹ 8.29 Lakh',
       '₹ 5.41 Lakh', '₹ 4.67 Lakh', '₹ 2.59 Lakh', '₹ 5.91 Lakh',
       '₹ 5.68 Lakh', '₹ 7.09 Lakh', '₹ 8.01 Lakh', '₹ 2.81 Lakh',
       '₹ 25.9 Lakh', '₹ 38.5 Lakh', '₹ 13.94 Lakh', '₹ 14.85 Lakh',
       '₹ 1.36 Crore', '₹ 10.09 Lakh', '₹ 86 Lakh', '₹ 16.06 Lakh',
       '₹ 15.49 Lakh', '₹ 11.36 Lakh', '₹ 42.85 Lakh', '₹ 11.67 Lakh',
       '₹ 4.43 Lakh', '₹ 15.11 Lakh', '₹ 7.34 Lakh', '₹ 47 Lakh',
       '₹ 22.9 Lakh', '₹ 5.05 Lakh', '₹ 2.75 Lakh', '₹ 4.92 Lakh',
       '₹ 20.99 Lakh', '₹ 39 Lakh', '₹ 31.43 Lakh', '₹ 3.34 Lakh',
       '₹ 13.41 Lakh', '₹ 55 Lakh', '₹ 18.65 Lakh', '₹ 1.71 Lakh',
       '₹ 31.5 Lakh', '₹ 34.9 Lakh', '₹ 10.8 Lakh', '₹ 2.36 Lakh',
       '₹ 24.95 Lakh', '₹ 62.5 Lakh', '₹ 31.89 Lakh', '₹ 41.9 Lakh',
       '₹ 10.85 Lakh', '₹ 6.97 Lakh', '₹ 9.23 Lakh', '₹ 7.24 Lakh',
       '₹ 3.98 Lakh', '₹ 60 Lakh', '₹ 8.7 Lakh', '₹ 5.32 Lakh',
       '₹ 16.58 Lakh', '₹ 44.75 Lakh', '₹ 69 Lakh', '₹ 4.56 Lakh',
       '₹ 6.77 Lakh', '₹ 26.15 Lakh', '₹ 8.89 Lakh', '₹ 7.06 Lakh',
       '₹ 12.95 Lakh', '₹ 6.47 Lakh', '₹ 9.35 Lakh', '₹ 64 Lakh',
       '₹ 8.38 Lakh', '₹ 8.76 Lakh'], dtype=object)

In [8]:
car['kms_driven'].unique()

array(['22,402 km', '10,344 km', '12,999 km', ..., '37,622 km',
       '64,726 km', '29,150 km'], dtype=object)

In [9]:
car['fuel_type'].unique()

array(['Petrol', 'Diesel', 'Diesel + 1', 'Electric', 'CNG', 'Petrol + 1',
       'Hybrid', 'LPG'], dtype=object)

In [10]:
backup=car.copy()

In [11]:
car=car[car['year_of_manufacture'].apply(lambda x: pd.to_numeric(x, errors='coerce')).notnull()]

In [12]:
car['car_price_in_rupees'] = car['car_price_in_rupees'].astype(str)
car['car_price_in_rupees'] = car['car_price_in_rupees'].str.replace('₹', '')
car['car_price_in_rupees'] = car['car_price_in_rupees'].str.replace('Lakh', '')
car['car_price_in_rupees'] = pd.to_numeric(car['car_price_in_rupees'], errors='coerce') * 100000
car['car_price_in_rupees']

0        445000.0
1        293000.0
2       2249000.0
3        695000.0
4       1200000.0
          ...
2100     360000.0
2101    2200000.0
2102     838000.0
2103     675000.0
2104     876000.0
Name: car_price_in_rupees, Length: 2105, dtype: float64

In [13]:
car.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2105 entries, 0 to 2104
Data columns (total 6 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   car_name             2105 non-null   object
 1   car_price_in_rupees  2098 non-null   float64
 2   kms_driven           2105 non-null   object
 3   fuel_type            2105 non-null   object
 4   city                 2105 non-null   object
 5   year_of_manufacture  2105 non-null   int64
dtypes: float64(1), int64(1), object(4)
memory usage: 98.8+ KB

In [14]:
# Replace NaN with 0 and convert to integers
car['car_price_in_rupees'] = car['car_price_in_rupees'].fillna(0).astype(int)

In [15]:
car.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2105 entries, 0 to 2104
Data columns (total 6 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   car_name             2105 non-null   object
 1   car_price_in_rupees  2105 non-null   int64
 2   kms_driven           2105 non-null   object
 3   fuel_type            2105 non-null   object
 4   city                 2105 non-null   object
 5   year_of_manufacture  2105 non-null   int64
dtypes: int64(2), object(4)
memory usage: 98.8+ KB

In [16]:
car['kms_driven'] = car['kms_driven'].astype(str)
car['kms_driven'] = car['kms_driven'].str.split(' ').str.get(0).str.replace(',', '')

In [17]:
car['kms_driven']=car['kms_driven'].astype(int)

In [18]:
car.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2105 entries, 0 to 2104
Data columns (total 6 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   car_name             2105 non-null   object
 1   car_price_in_rupees  2105 non-null   int64
 2   kms_driven           2105 non-null   int64
 3   fuel_type            2105 non-null   object
 4   city                 2105 non-null   object
 5   year_of_manufacture  2105 non-null   int64
dtypes: int64(3), object(3)
memory usage: 98.8+ KB

In [19]:
car[car['fuel_type'].isna()]

Empty DataFrame
Columns: [car_name, car_price_in_rupees, kms_driven, fuel_type, city, year_of_manufacture]
Index: []

In [20]:
car['car_name']=car['car_name'].str.split(' ').str.slice(0,3).str.join(' ')

In [21]:
car.reset_index(drop=True)

,car_name,car_price_in_rupees,kms_driven,fuel_type,city,year_of_manufacture
0,Hyundai Grand i10,445000,22402,Petrol,Mumbai,2016
1,Maruti Suzuki Alto,293000,10344,Petrol,Kolkata,2019
2,Tata Safari XZ,2249000,12999,Diesel,Bangalore,2021
3,Maruti Suzuki Ciaz,695000,45000,Petrol,Thane,2016
4,Jeep Compass Sport,1200000,11193,Petrol,Kolkata,2019
...,...,...,...,...,...,...
2100,Ford Figo Titanium1.5,360000,42158,Diesel,Kolkata,2015
2101,MINI Cooper Countryman,2200000,68862,Diesel,Hyderabad,2013
2102,Hyundai Verna 1.6,838000,37622,Petrol,Chennai,2018
2103,Maruti Suzuki Ciaz,675000,64726,Petrol,Mumbai,2017
2104,Hyundai Verna 1.6,876000,29150,Petrol,Pune,2017

In [22]:
car.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2105 entries, 0 to 2104
Data columns (total 6 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   car_name             2105 non-null   object
 1   car_price_in_rupees  2105 non-null   int64
 2   kms_driven           2105 non-null   int64
 3   fuel_type            2105 non-null   object
 4   city                 2105 non-null   object
 5   year_of_manufacture  2105 non-null   int64
dtypes: int64(3), object(3)
memory usage: 98.8+ KB

In [23]:
car.describe()

       car_price_in_rupees    kms_driven  year_of_manufacture
count         2.105000e+03  2.105000e+03          2105.000000
mean          1.098663e+06  4.830131e+04          2017.022803
std           1.186164e+06  8.372047e+04             2.818066
min           0.000000e+00  6.400000e+01          2004.000000
25%           4.750000e+05  2.499300e+04          2015.000000
50%           6.950000e+05  4.282500e+04          2017.000000
75%           1.150000e+06  6.300000e+04          2019.000000
max           9.500000e+06  3.600000e+06          2022.000000

In [24]:
car[car['car_price_in_rupees']>6e6]

,car_name,car_price_in_rupees,kms_driven,fuel_type,city,year_of_manufacture
17,Mercedes-Benz EQC 400,9500000,3200,Electric,Pune,2022
42,Mercedes-Benz EQC 400,8100000,21500,Electric,Bangalore,2020
63,Mercedes-Benz GLC 200,6600000,16785,Petrol,Bangalore,2021
64,Mercedes-Benz E-Class E,6898999,3999,Petrol,Bangalore,2020
212,Mercedes-Benz E-Class E,6175000,19070,Diesel,Bangalore,2019
270,Mercedes-Benz GLS 350,6800000,88000,Diesel,Hyderabad,2018
300,Porsche Cayenne Turbo,7856999,12000,Petrol,Ahmedabad,2015
308,Land Rover Range,7700000,5600,Petrol,Thane,2021
336,Mercedes-Benz AMG GLA35,6450000,2000,Petrol,Chennai,2022
394,Jeep Wrangler Rubicon,6500000,27340,Petrol,Hyderabad,2021
426,Land Rover Range,7700000,39800,Petrol,Thane,2019
566,Audi Q7 Technology,9300000,6500,Petrol,Pune,2022
642,Land Rover Range,7898999,31059,Petrol,Kolkata,2020
663,Audi Q7 45,6150000,40000,Diesel,Ahmedabad,2017
674,Mercedes-Benz E-Class E,7400000,11000,Diesel,Delhi,2022
768,BMW 7 Series,6975000,22000,Diesel,Ahmedabad,2017
862,Mercedes-Benz AMG GLA35,6100000,1600,Petrol,Mumbai,2021
1184,Mercedes-Benz GLC 220d,6498999,6563,Diesel,Kolkata,2022
1198,Audi Q7 45,6995000,37648,Diesel,Bangalore,2018
1218,Mercedes-Benz GLS 350,6300000,59348,Diesel,Mumbai,2017
1257,Land Rover Range,8500000,29000,Petrol,Faridabad,2020
1528,Audi A6 2.0,7200000,20000,Petrol,Bangalore,2021
1651,Land Rover Range,7700000,5600,Petrol,Thane,2021
1688,Toyota Land Cruiser,7000000,152000,Diesel,Pune,2011
1860,Mercedes-Benz GLE 300d,8600000,34000,Diesel,Pune,2020
1968,BMW X4 xDrive20d,6250000,13600,Diesel,Ahmedabad,2020
2037,BMW 5 Series,6800000,9664,Petrol,Mumbai,2022
2053,Mercedes-Benz S-Class S,6900000,18000,Diesel,Ahmedabad,2017
2060,Bentley Continental GT,7000000,19506,Petrol,Hyderabad,2008
2097,Land Rover Discovery,6400000,8500,Petrol,Ahmedabad,2021

In [25]:
car[car['car_price_in_rupees']<6e6].reset_index(drop=True)

,car_name,car_price_in_rupees,kms_driven,fuel_type,city,year_of_manufacture
0,Hyundai Grand i10,445000,22402,Petrol,Mumbai,2016
1,Maruti Suzuki Alto,293000,10344,Petrol,Kolkata,2019
2,Tata Safari XZ,2249000,12999,Diesel,Bangalore,2021
3,Maruti Suzuki Ciaz,695000,45000,Petrol,Thane,2016
4,Jeep Compass Sport,1200000,11193,Petrol,Kolkata,2019
...,...,...,...,...,...,...
2069,Ford Figo Titanium1.5,360000,42158,Diesel,Kolkata,2015
2070,MINI Cooper Countryman,2200000,68862,Diesel,Hyderabad,2013
2071,Hyundai Verna 1.6,838000,37622,Petrol,Chennai,2018
2072,Maruti Suzuki Ciaz,675000,64726,Petrol,Mumbai,2017
2073,Hyundai Verna 1.6,876000,29150,Petrol,Pune,2017

In [26]:
car.to_csv('Cleaned Car.csv')

In [27]:
X=car.drop(columns='car_price_in_rupees')
y=car['car_price_in_rupees']

In [28]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2)

In [29]:
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import make_column_transformer
from sklearn.pipeline import make_pipeline

In [30]:
ohe=OneHotEncoder()
ohe.fit(X[['car_name','city','fuel_type']])

OneHotEncoder()

In [31]:
column_trans=make_column_transformer((OneHotEncoder(categories=ohe.categories_),['car_name','city','fuel_type']),remainder='passthrough')

In [32]:
lr=LinearRegression()

In [33]:
pipe=make_pipeline(column_trans,lr)

In [34]:
pipe.fit(X_train,y_train)

Pipeline(steps=[('columntransformer',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('onehotencoder',
                                                  OneHotEncoder(categories=[array(['Audi A3 35', 'Audi A3 40', 'Audi A4 2.0', 'Audi A4 3.0',
       'Audi A4 35', 'Audi A4 Technology', 'Audi A6 2.0', 'Audi A6 35',
       'Audi A6 Technology', 'Audi A8 L', 'Audi Q2 Premium',
       'Audi Q3 2.0', 'Audi Q3 30', 'Audi Q3 35', 'Audi Q5 2.0',
       'Audi Q5 3.0', 'Audi...
                                                                            array(['Ahmedabad', 'Ambattur', 'Bangalore', 'Chennai', 'Delhi',
       'Faridabad', 'Gurgaon', 'Hyderabad', 'Kolkata', 'Mumbai', 'Noida',
       'Pallikarnai', 'Poonamallee', 'Pune', 'Thane', 'Thiruvallur'],
      dtype=object),
                                                                            array(['CNG', 'Diesel', 'Diesel + 1', 'Electric', 'Hybrid', 'LPG',
       'Petrol', 'Petrol + 1'], dtype=object)]),
                                                  ['car_name', 'city',
                                                   'fuel_type'])])),
                ('linearregression', LinearRegression())])

In [35]:
# Assuming 'pipe' is your pipeline, and X_train, y_train are your training data
pipe.fit(X_train, y_train)

# Now you can use the predict method
y_pred = pipe.predict(X_test)

In [36]:
r2_score(y_test,y_pred)

0.29759526689397386

In [37]:
scores=[]
for i in range(1000):
  X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=i)
  lr=LinearRegression()
  pipe=make_pipeline(column_trans,lr)
  pipe.fit(X_train,y_train)
  y_pred=pipe.predict(X_test)

  scores.append(r2_score(y_test,y_pred))

In [38]:
np.argmax(scores)

797

In [39]:
scores[np.argmax(scores)]

0.5452377778849696

In [40]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=np.argmax(scores))
lr=LinearRegression()
pipe=make_pipeline(column_trans,lr)
pipe.fit(X_train,y_train)
y_pred=pipe.predict(X_test)
r2_score(y_test,y_pred)

0.5452377778849696

In [41]:
import pickle

In [42]:
pickle.dump(pipe,open('LinearRegressionModel.pkl','wb'))

In [43]:
pipe.predict(pd.DataFrame([['Maruti Suzuki Swift', 100, 'Petrol', 'Thane', 2019]], columns=['car_name', 'kms_driven', 'fuel_type', 'city', 'year_of_manufacture']))

array([505175.30158076])

In [44]:
from google.colab import files

files.download('Cleaned Car.csv')

In [45]:
from google.colab import files

files.download('LinearRegressionModel.pkl')